altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  bc0bdcd7-5afa-442a-8271-f7f7ab148cfa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ecb7dbac-4fe7-4e46-be46-fa42583461b6
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 007811e7-d155-4ba1-bc59-29b99efcb140
        userCondition: null
fs: companyInfo
handle: companyInfo
name: 'Company Info'
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
